### ISSUE TITLE
Improve implicit convertion

### ISSUE THREAD

**Issue by letientai299** [ReactiveX/RxScala#195] opened 2016-06-11 04:33 UTC
The following Scala code won't compile

``` scala
import rx.lang.scala.Observable
object Solution {
  def main(args: Array[String]): Unit = {
    Observable.create[Int](s => s.onNext(1))
      .subscribe(println(_))
  }
}
```

While the same thing in Java works fine. 

``` java
import rx.Observable;
public class Main {
  public static void main(String[] args) {
    Observable.create(s -> s.onNext(0))
        .subscribe(System.out::println);
  }
}
```

Also, in the following compilable version, we shouldn't have to explicit add `Int` as the type param;

``` scala
import rx.lang.scala.{Observable, Subscriber}
object Solution {
  def main(args: Array[String]): Unit = {
    Observable.create[Int](
      s => {
        s.onNext(1)
        Subscriber()
      }
    )
      .subscribe(println(_))
  }
}

```

**Edit**
Remove the redundant call to `Scheduers.newThread()` in the last snippet. That's related to another issues I reported to Jetbrains (you can find it [here](https://youtrack.jetbrains.com/issue/SCL-10413)).

**Comment by zsxwing** [comment] 2016-06-11 07:10
Actually, the Java compiler doesn't infer the correct type. It just thinks that `s` is `java.lang.Object`. You can change your codes as follows:

```
Observable.create(s -> s.onNext(0))
            .subscribe(i -> System.out.println(i + 1));
```

and it cannot be compiled.

I'm not sure how the Scala compiler works. But maybe the Scala compiler behavior is better as it refuses to use a wrong type in such case.

**Comment by letientai299** [comment] 2016-06-11 11:31
Thanks @zsxwing for pointing out that `i` (in your example) is just `java.lang.Object`. By, adding `<Integer>` into the method, the code can compile.

``` java
Observable.<Integer>create(s -> s.onNext(0))
            .subscribe(i -> System.out.println(i + 1));
```

So `Int` is needed to make Scala compiler understand that `s` is `Observer[Int]`. 

But `s => s.onNext(0)` is `Observer[Int] => Unit`, and therefor, the Scala code still cannot compile without `Subscriber()`.  That statement is nothing but make the code more verbose compare to the Java version. 

Anyway we could improve that?

**Comment by samuelgruetter** [comment] 2016-06-11 20:11
The problem is that in order to translate a Java program doing `Observable.xxx` to Scala, you can't always just write `Observable.xxx` in Scala, because some methods have different names. So you should read the [comparison table](http://reactivex.io/rxscala/comparison.html), which contains the following line:

| Java method | Scala method |
| --- | --- |
| `create(OnSubscribe<T>)` | `apply(Subscriber[T] => Unit)` |

So you can write your example in Scala as follows:

``` scala
Observable.apply[Int](s => s.onNext(1))
      .subscribe(println(_))
```

or equivalently

``` scala
Observable((s: Subscriber[Int]) => s.onNext(1))
      .subscribe(println(_))
```

The `create` method of the Scala Observable is a relict of ancient times, when you passed an `Observer[T] => Subscription` function to `create` instead of a `Subscriber[T] => Unit` function. This relict was removed in RxJava, but not in RxScala.

I agree that this is confusing and should be improved, thank you for pointing it out. I suggested to change this [here](https://github.com/ReactiveX/RxJava/issues/1340#issuecomment-225391215).

**Comment by zsxwing** [comment] 2016-06-17 04:01
Closing this since Observable.create has been deprecated in #196

**Closed as completed** 2016-06-17 04:01 UTC
